// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzoqawvkevdkfrredyen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6b3Fhd3ZrZXZka2ZycmVkeWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTIzNjIsImV4cCI6MjA2Mjc4ODM2Mn0.YN6Zp721pD0IEmso3QLBpplEysmd3vvc8CN_tq8G-Hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);